services:
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000